#!/usr/bin/env python3
"""Reproducible synthetic-v1 fixture; no network, dependencies, secrets or DB access."""
import argparse
import csv
import hashlib
import io
import json
import random
from datetime import datetime, timedelta, timezone
from pathlib import Path

SEED = 20260601
START = datetime(2026, 6, 1, tzinfo=timezone.utc)
REGIONS = ('north', 'south', 'east', 'west')
COLUMNS = {
    'customers': ('id', 'customer_segment', 'region', 'created_at'),
    'transactions': ('id', 'customer_id', 'transaction_date', 'amount', 'transaction_type', 'channel', 'merchant_category', 'region', 'status', 'created_at'),
    'pipeline_runs': ('id', 'pipeline_name', 'started_at', 'completed_at', 'records_processed', 'records_rejected', 'status', 'error_code', 'error_message'),
    'data_quality_events': ('id', 'detected_at', 'dataset_name', 'issue_type', 'severity', 'affected_records', 'description'),
    'deployments': ('id', 'service_name', 'version', 'deployed_at', 'status'),
}


def stamp(value):
    return value.isoformat(timespec='seconds')


def build_dataset():
    rng = random.Random(SEED)
    data = {name: [] for name in COLUMNS}
    for region_idx, region in enumerate(REGIONS):
        for index in range(100):
            data['customers'].append((region_idx * 100 + index + 1,
                ('retail', 'premium', 'small_business')[index % 3], region,
                stamp(START - timedelta(days=365 - index))))
    for day_idx in range(56):
        day = START + timedelta(days=day_idx)
        decline = 14 <= day_idx < 21  # June 15–21 inclusive
        regional = 35 <= day_idx < 42  # July 6–12 inclusive
        daily = []
        for region_idx, region in enumerate(REGIONS):
            for index in range(25 if decline else 50):
                when = day + timedelta(hours=8, seconds=region_idx * 3600 + index * 60)
                null_category = day_idx in (44, 45) and region_idx == 0 and index < 10
                malformed = day_idx == 46 and region_idx == 0 and index < 10
                daily.append((0, region_idx * 100 + rng.randrange(100) + 1,
                    stamp(when), f'{rng.randrange(500, 50001) / 100:.2f}',
                    rng.choice(('purchase', 'purchase', 'purchase', 'refund', 'transfer')),
                    '??invalid??' if malformed else rng.choice(('web', 'mobile', 'branch')),
                    None if null_category else rng.choice(('grocery', 'travel', 'dining', 'retail', 'utilities')),
                    region, 'declined' if index < (40 if regional and region == 'east' else 2) else 'settled',
                    stamp(when + timedelta(seconds=30))))
        if 23 <= day_idx < 26:  # June 24–26: replay twenty business events/day
            for original in daily[:20]:
                replayed_at = datetime.fromisoformat(original[-1]) + timedelta(minutes=5)
                daily.append(original[:-1] + (stamp(replayed_at),))
        for row in daily:
            data['transactions'].append((len(data['transactions']) + 1,) + row[1:])
        data['pipeline_runs'].append((day_idx + 1, 'transaction_ingestion',
            stamp(day + timedelta(hours=23)), stamp(day + timedelta(hours=23, minutes=5)),
            len(daily), 102 if decline else 2, 'partial' if decline else 'completed',
            'SCHEMA_VALIDATION' if decline else None,
            'Source payload validation rejected records.' if decline else None))
    data['data_quality_events'] = [
        (1, '2026-06-21T23:10:00+00:00', 'transactions', 'rejected_records', 'critical', 714,
         '714 input records rejected by daily ingestion runs during June 15–21 UTC.'),
        (2, '2026-06-26T23:10:00+00:00', 'transactions', 'duplicate_business_event', 'warning', 60,
         '60 excess rows share business attributes with earlier ingested events during June 24–26 UTC.'),
        (3, '2026-07-16T23:10:00+00:00', 'transactions', 'missing_merchant_category', 'warning', 20,
         '20 records with missing merchant_category during July 15–16 UTC.'),
        (4, '2026-07-17T23:10:00+00:00', 'transactions', 'malformed_channel', 'warning', 10,
         '10 records contain an unrecognized channel on July 17 UTC.'),
    ]
    data['deployments'] = [
        (1, 'transaction_ingestion', '2.4.0', '2026-06-14T23:45:00+00:00', 'succeeded'),
        (2, 'transaction_ingestion', '2.4.1', '2026-06-22T00:00:00+00:00', 'succeeded'),
        (3, 'reporting', '1.8.0', '2026-07-20T07:00:00+00:00', 'succeeded'),
    ]
    return data


def render_sql(data):
    out = io.StringIO(newline='')
    out.write('-- Generated by database/synthetic-data/generate.py; entirely synthetic.\n')
    out.write('-- Fixed UTC dates, seed 20260601, dataset synthetic-v1. Do not hand-edit.\n')
    for table, columns in COLUMNS.items():
        out.write(f"COPY analytics.{table} ({', '.join(columns)}) FROM STDIN WITH (FORMAT csv, NULL '\\N');\n")
        writer = csv.writer(out, lineterminator='\n')
        writer.writerows(tuple('\\N' if value is None else value for value in row) for row in data[table])
        out.write('\\.\n')
    return out.getvalue()


def artifacts():
    data = build_dataset()
    sql = render_sql(data)
    manifest = {
        'dataset_version': 'synthetic-v1', 'seed': SEED,
        'start_inclusive_utc': stamp(START),
        'end_exclusive_utc': stamp(START + timedelta(days=56)),
        'rows': {table: len(rows) for table, rows in data.items()},
        'sha256': hashlib.sha256(sql.encode('utf-8')).hexdigest(),
    }
    return sql, json.dumps(manifest, indent=2, sort_keys=True) + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if committed artifacts differ; do not write.')
    parser.add_argument('--output-dir', type=Path, default=Path(__file__).resolve().parents[1] / 'seed')
    args = parser.parse_args()
    sql, manifest = artifacts()
    for name, text in [('synthetic-v1.sql', sql), ('manifest.json', manifest)]:
        path = args.output_dir / name
        if args.check:
            if not path.is_file() or path.read_bytes() != text.encode('utf-8'):
                parser.exit(1, f'Outdated or missing generated fixture: {path}\n')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(text.encode('utf-8'))
    print(manifest, end='')


if __name__ == '__main__':
    main()
